### PR TITLE
Backports needed for gnocchi

### PR DESCRIPTION
**Pull request by dchavoll**
These 14 commits are backports to starlingX-staging, that are required to enable delivery of the gnocchi feature.

This activity corresponds to the following task in StoryBoard:

“[Enhancement] Various backports to core openstack components to pick up fixes”
https://storyboard.openstack.org/#!/story/2003407

The commits, all cleanly backported are:

228517e0c2bf04f5766baff54bcb58e55ab266d6 Replace the Gnocchi dispatcher by a publisher
886dc38d912ca6b01320d9c8e2d61448c9e3700b Replace jsonutils by ujson
992efae39bedbe66d2ce2a8a2b6238e4068a213a simplify cache generation
5ebc2509ad2b9075acc56ee025f9eb122e7a21ee Replace ujson with json
e516e82512c32d6a9415c4f48b196219b7469b17 use hashmap to quickly find matching resource def
7275dd59124260df18bb6d3f78b2737297fe298d compute sample as dictionary once
c473be465b87db1250e5bb01dee7e7a505e3b4ad fix gnocchi stats logging
e58fe242bc0a63ba4e67ed662399015c51eb6b42 simplify gnocchi batch push setup
7838fe00a7172e5785c19c4c48b1d5c4e7dd18a0 Cached should not be used when creating gnocchi resources
64f36fcaff1a55c62cc6cbf235f46a98664cb8fe set cache with attributes only
bb4692dfdc9d8b8ec8eeaaf0356e812574c57937 gnocchi: configure archive policies on Ceilo side
717e96830ab0d3bb92f6e6a785fcacc62ab1b9f4 Don't use gnocchiclient during publisher init
27064b630652d2a0f3d80fd336c846fe2a9d5e6c fix gnocchi publisher
10cd6ba713be5c15d4de29f24a0c7d0120f95ee2 gnocchi: don't create metrics with resource

Testing: Code compiles successfully

### CODE REVIEW

**Comment by Missxiaoguo** [comment]
Looks all good.

**Comment by dchavoll** [comment]
@dtroyer 
All these backport commits are required by Gnocchi.
Can you please review them and merge them if you find them ok?

**Comment by dtroyer** [comment]
I am OK with the set of backports, I would ask that you keep the original commit message and add a pointer to the source of each commit and to the story directly in the commit messages so that linkage can be traced in the future.  Github PR messages are not kept in the repo and all of that information is left behind in a git clone for example.  If changes to the original commit were necessary add a mention of that also.

The practice when cherry-picking/backporting changes in OpenStack is to keep the Commit-ID the same also as that allows Gerrit to do some useful things.  Since these repos are not in Gerrit we lose that bit but for the sake of consistency I would advise we keep the original Comit-ID also.

**Comment by dtroyer** [comment]
LGTM

Thanks for the commit message updates.  Note that the 'cherry-pick' commit SHAs are for an older internal repo and are not publicly available, in the future let's label those as internal or something so people do not expect they will be visible.

**Pull request merged**
